const express = require('express');
const multer = require('multer');
const archiver = require('archiver');
const crypto = require('crypto');
const fsp = require('fs/promises');
const path = require('path');
const app = express();
const port = Number(process.env.PORT || 3017);
const host = process.env.HOST || '0.0.0.0';
const storageRoot = path.resolve(process.env.SIGN_STORAGE_DIR || path.join(process.cwd(), 'storage'));
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 50 * 1024 * 1024 } });
app.disable('x-powered-by');
app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(process.cwd(), 'public')));
function decodeUploadFileName(fileName) { const value = String(fileName || ''); if (!value) return value; if (/^[\u0000-\u007F]*$/.test(value)) return value; if (!/[ÐÑ]/.test(value)) return value; try { return Buffer.from(value, 'latin1').toString('utf8'); } catch { return value; } }
function safeFileName(fileName, fallback = 'document.bin') { const raw = String(fileName || fallback).replace(/[\\/]+/g, '_').replace(/[\x00-\x1F\x7F]+/g, ' ').trim(); const cleaned = raw.replace(/\s+/g, ' ').replace(/^\.+/, '').trim(); return cleaned || fallback; }
function redact(obj) { if (!obj || typeof obj !== 'object') return obj || null; const out = {}; for (const [k,v] of Object.entries(obj)) { if (/(password|pass|pin|secret)/i.test(k)) continue; out[k] = v; } return out; }
function sha256(buffer) { return crypto.createHash('sha256').update(buffer).digest('hex'); }
function recordPath(documentId) { return path.join(storageRoot, documentId, 'record.json'); }
async function ensureDir(dirPath) { await fsp.mkdir(dirPath, { recursive: true }); }
async function loadRecord(documentId) { return JSON.parse(await fsp.readFile(recordPath(documentId), 'utf8')); }
async function saveRecord(documentId, record) { await ensureDir(path.dirname(recordPath(documentId))); await fsp.writeFile(recordPath(documentId), JSON.stringify(record, null, 2)); }
app.get('/api/health', (_req, res) => res.json({ ok: true, service: 'VilnoCheck-SignService', version: '0.1.0', methods: ['hardware-token','file-key','cloud'] }));
app.get('/api/bootstrap', (_req, res) => res.json({ ok: true, methods: [{ id: 'hardware-token', title: 'Апаратний токен', status: 'prototype' }, { id: 'file-key', title: 'Файловий ключ', status: 'prototype' }, { id: 'cloud', title: 'Хмарний підпис', status: 'planned' }] }));
app.post('/api/documents', upload.single('document'), async (req, res, next) => { try { if (!req.file || !req.file.buffer?.length) return res.status(400).json({ error: 'document file is required' }); const documentId = crypto.randomUUID(); const originalName = safeFileName(decodeUploadFileName(req.file.originalname) || 'document.bin'); const directory = path.join(storageRoot, documentId); const originalPath = path.join(directory, originalName); await ensureDir(directory); await fsp.writeFile(originalPath, req.file.buffer); const record = { id: documentId, createdAt: new Date().toISOString(), document: { originalName, mimeType: req.file.mimetype || 'application/octet-stream', size: req.file.buffer.length, sha256: sha256(req.file.buffer), path: originalPath }, session: null, signature: null }; await saveRecord(documentId, record); res.json({ ok: true, documentId, fileName: originalName, mimeType: record.document.mimeType, size: record.document.size, sha256: record.document.sha256, signingPayloadBase64: req.file.buffer.toString('base64') }); } catch (error) { next(error); } });
app.patch('/api/documents/:documentId/session', async (req, res, next) => { try { const record = await loadRecord(req.params.documentId); record.session = redact(req.body || {}); record.session.updatedAt = new Date().toISOString(); await saveRecord(req.params.documentId, record); res.json({ ok: true, documentId: req.params.documentId, session: record.session }); } catch (error) { if (error?.code === 'ENOENT') return res.status(404).json({ error: 'document not found' }); next(error); } });
app.post('/api/documents/:documentId/signature', async (req, res, next) => { try { const { signatureBase64, signatureInfo, signatureFileName, method, methodState, client } = req.body || {}; if (!signatureBase64 || typeof signatureBase64 !== 'string') return res.status(400).json({ error: 'signatureBase64 is required' }); const record = await loadRecord(req.params.documentId); const signatureBuffer = Buffer.from(signatureBase64, 'base64'); const signatureName = safeFileName(signatureFileName || `${record.document.originalName}.p7s`, 'signature.p7s'); const signaturePath = path.join(storageRoot, req.params.documentId, signatureName); await fsp.writeFile(signaturePath, signatureBuffer); record.signature = { uploadedAt: new Date().toISOString(), fileName: signatureName, size: signatureBuffer.length, sha256: sha256(signatureBuffer), path: signaturePath, signatureInfo: signatureInfo || null, method: method || null, methodState: redact(methodState), client: redact(client) }; await saveRecord(req.params.documentId, record); res.json({ ok: true, documentId: req.params.documentId, downloadUrl: `/api/documents/${req.params.documentId}/package` }); } catch (error) { if (error?.code === 'ENOENT') return res.status(404).json({ error: 'document not found' }); next(error); } });
app.get('/api/documents/:documentId/package', async (req, res, next) => { try { const record = await loadRecord(req.params.documentId); if (!record.signature?.path) return res.status(409).json({ error: 'signature has not been uploaded yet' }); res.setHeader('Content-Type', 'application/zip'); res.setHeader('Content-Disposition', 'attachment; filename="signed-package.zip"'); const archive = archiver('zip', { zlib: { level: 9 } }); archive.on('error', next); archive.pipe(res); archive.file(record.document.path, { name: record.document.originalName }); archive.file(record.signature.path, { name: record.signature.fileName }); archive.append(JSON.stringify({ generatedAt: new Date().toISOString(), service: 'VilnoCheck-SignService', documentId: record.id, document: { fileName: record.document.originalName, mimeType: record.document.mimeType, size: record.document.size, sha256: record.document.sha256 }, session: record.session, signature: { fileName: record.signature.fileName, size: record.signature.size, sha256: record.signature.sha256, uploadedAt: record.signature.uploadedAt, method: record.signature.method, methodState: record.signature.methodState, signatureInfo: record.signature.signatureInfo } }, null, 2), { name: 'manifest.json' }); await archive.finalize(); } catch (error) { if (error?.code === 'ENOENT') return res.status(404).json({ error: 'package not found' }); next(error); } });
app.get('*', (req, res) => { if (req.path.startsWith('/api/')) return res.status(404).json({ error: 'not found' }); res.sendFile(path.join(process.cwd(), 'public', 'index.html')); });
app.use((error, _req, res, _next) => { console.error('[VilnoCheck-SignService]', error); res.status(500).json({ error: error?.message || 'internal server error' }); });
ensureDir(storageRoot).then(() => app.listen(port, host, () => console.log(`[VilnoCheck-SignService] listening on http://${host}:${port}`))).catch((error) => { console.error(error); process.exit(1); });
